### ISSUE TITLE
npmパッケージをアップデートする

### ISSUE THREAD

**Issue by oka4shi** [sohosai/teaser23#12]
## @typescript-eslint/parser: 5.62.0→6.0.0
[6.0.0でのBreaking change](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#user-facing-breaking-changes)を見る感じ特に問題はなさそうです。

## prettier: 2.8.8→3.0.0
[3.0.0での変更点](https://prettier.io/blog/2023/07/05/3.0.0.html)

trailingCommaのデフォルト値がes5からallになったようですが、これまでの設定のes5を維持したいと思います。

prettier-plugin-astroも[v0.11](https://github.com/withastro/prettier-plugin-astro/releases/tag/v0.11.0)で3.0.0に対応済み。

## 保留：astro-i18n-aut: 0.0.17→0.1.15
**保留します**。かなり大規模な更新が入って、ユーティリティーが複数追加されてるようです。Ryogaさんによる拡張と被る部分もあるので、とりあえず更新は保留しておきます。

## semver: 6.3.0→6.3.1
semver3.6.0に脆弱性があると[dependsabotから警告](https://github.com/sohosai/teaser23/security/dependabot/1)されました。これに依存しているパッケージがあったようです。今回のアップデートで6.3.1に更新済みです。

**Comment by oka4shi** [comment]
Prettierが3.0.0になったことで、なぜかAstroファイルがフォーマットされなくなる問題に今更気づきました。
prettier-plugin-astroもv0.11で対応したようですが、なぜか動きません。詳細は現在調査中です。

**Comment by Ryoga-exe** [comment]
私の環境でも発生しました。

> Prettierが3.0.0になったことで、なぜかAstroファイルがフォーマットされなくなる問題に今更気づきました。 prettier-plugin-astroもv0.11で対応したようですが、なぜか動きません。詳細は現在調査中です。

**Comment by oka4shi** [comment]
astro-i18n-autはアップデート済み。
また、Prettier問題も c160f92966b5a9f49a1accc94ac2586c7a5d13ab で解決。
