### ISSUE TITLE
フォントの導入

### ISSUE THREAD

**Issue by Ryoga-exe** [sohosai/teaser23#16]
Google Font なりで良さげなフォントを導入する

**Comment by Ryoga-exe** [comment]
現在の teaser サイトで使われているフォントは `Zen Maru Gothic` と `ryo-gothic-plusn` と `museo-sans`

**Comment by Ryoga-exe** [comment]
https://github.com/sohosai/teaser/blob/master/src/components/MainContent.tsx#L70-L74

**Comment by Ryoga-exe** [comment]
[公式ドキュメント](https://docs.astro.build/ja/guides/fonts/)では Fontsource を入れる方法が紹介されている

[astro-google-fonts-optimizer](https://github.com/sebholstein/astro-google-fonts-optimizer) というプラグインもある

とりあえず前者で実装後、両者のパフォーマンスを検証して比較

**Comment by oka4shi** [comment]
Heroなどのフォント: Zen Maru Gothic
その他の和文: お使いの端末のフォント(ヒラギノ→Noto Sans→游ゴシック→その他)
欧文フォント: Mulish
という方針になりました。
