### ISSUE TITLE
SNSへのリンクが欲しいかも

### ISSUE THREAD

**Issue by appare45** [sohosai/teaser23#50]

**Comment by oka4shi** [comment]
![A](https://github.com/sohosai/teaser23/assets/67847553/58cf08fc-c987-4bce-b248-c686d6a27d14)
![B](https://github.com/sohosai/teaser23/assets/67847553/b29b8480-cbd4-4fc4-a605-677cad2f625c)

上or下、どっちのデザインがいいと思いますか？

**Comment by appare45** [comment]
個人的には下かな？
