### ISSUE TITLE
翻訳ファイル上の改行コードをbrタグやpタグに変換する

### ISSUE THREAD

**Issue by oka4shi** [sohosai/teaser23#6]
改行1つ：`<br>`
改行2つ：新しい段落(`<p>`で囲む)
というような機能がほしい。

実装方法の候補
- t()がbrタグやpタグを追加して返す
  - 比較的簡単に実装できそう
- 組版システム上に実装する
  - そもそも組版システムを現行の準備期間サイトから移植するところから始めないといけない
- 普通に関数を作ってutilとかに置いておく
- `white-space: pre-wrap`
  - 実装が簡単
  - 段落がpタグで囲まれないという問題がある
 - Markdownを採用して、HTML変換する

**Comment by Ryoga-exe** [comment]
適当な関数を作って `set:html` を使って流し込むのが現実的？

https://docs.astro.build/ja/reference/directives-reference/#sethtml

**Comment by oka4shi** [comment]
もしくは、[tsxをエクスポート](https://docs.astro.build/ja/guides/imports/#jsx--tsx)する関数を作るのもあり。

**Comment by oka4shi** [comment]
段落は翻訳ファイルで配列で表し、改行はCSSで`white-space: pre-line;`を指定する方法で実装した。
